### ISSUE TITLE
Mountain Lion installing

### ISSUE THREAD

**Issue by jcdalton2201** [mariano/node-db-oracle#49]
i've been trying to get this module to compile with OSX 10.8.2  I've tried both the 11.2 and 10.2 oracle lib and for both 32 and 64 bit but keep getting the same error.
ld: warning: ignoring file /opt/instantclient//libnnz10.dylib, file was built for unsupported file format ( 0xcf 0xfa 0xed 0xfe 0x 7 0x 0 0x 0 0x 1 0x 3 0x 0 0x 0 0x 0 0x 6 0x 0 0x 0 0x 0 ) which is not the architecture being linked (i386): /opt/instantclient//libnnz10.dylib
Undefined symbols for architecture i386:
  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture i386

not sure where to go on this one.

**Comment by hsunsnippet** [comment]
The root cause is this: https://github.com/joyent/node/issues/3633
